### ISSUE TITLE
Explore CouchDB hosting for EPP cluster env

### ISSUE THREAD

**Issue by scottaubrey** [elifesciences/enhanced-preprints-server#197]
# Description

To reduce technical burden, we wish to reduce the number of database backends. Current SQLite is in use in the cluster to easy infrastructure maintenance, but we should explore using CouchDB to allow us to remove SQLite.

# Todo
- [x] Explore CouchDB SaaS offerings
- [x] Explore CouchDB Cluster offerings
- [x] Install CouchDB Helm chart on `flux-test` cluster (https://github.com/elifesciences/elife-flux-test/pull/409)
- [x] Create a new deployment of EPP to CouchDB in `flux-test` cluster for testing (https://github.com/elifesciences/elife-flux-test/pull/430)
- [x] Benchmark instance performance, to get an idea of differences between them
- [x] Test instance for obvious bugs 
- [x] #190 
- [x] #193 
- [ ] Investigate and Prepare permanent storage (EBS) for CouchDB cluster
- [ ] Provision an S3 bucket for CouchDB backup
- [ ] Investigate and create data backup schedule, and test restoration. 
- [ ] Document playbooks for operating CouchDB on the cluster
- [ ] Convert existing EPP deployment to CouchDB

**Comment by scottaubrey** [comment]
CouchDB SaaS offerings include:
- IBM coundant offerings
- Couchbase commercial DB on AWS marketplace
- A range of third-party repackging on AWS marketplace.

These might come in handy in the future, but they're all a bit expensive, and we're basically able to rebuild the whole thing from scratch right now. Decided it might be better to look at cluster-hosted CouchDB for now.

**Comment by scottaubrey** [comment]
The options for in-cluster are

- Couchbase offer an operator for their commercial offering
- official Apache CouchDB helm chart / docker image

For now, sticking with the helm chart.

**Comment by scottaubrey** [comment]
For basic benchmark, I ran a container on the cluster, making sure to run it on the node that isn't running either EPP node.:

`kubectl run --rm -it --image ubuntu:20.04 --overrides='{"apiVersion": "v1", "spec": {"nodeSelector": { "kubernetes.io/hostname": "ip-10-0-11-137.ec2.internal" }}}' benchmarking`

I then ran this bash script:
```
#!/bin/bash
set -e


for iter in 1 2 3; do
    echo "testing SQLite $iter..."
    echo "SQLite,$iter,$(ab -c1   -t 20 http://epp-node-http.epp:3000/article/10.1101/2022.03.15.484463 2>&1 | grep 'Requests per second:' | awk '{print $4}'),\
$(ab -c10  -t 20 http://epp-node-http.epp:3000/article/10.1101/2022.03.15.484463 2>&1 | grep 'Requests per second:' | awk '{print $4}'),\
$(ab -c20  -t 20 http://epp-node-http.epp:3000/article/10.1101/2022.03.15.484463 2>&1 | grep 'Requests per second:' | awk '{print $4}'),\
$(ab -c50  -t 20 http://epp-node-http.epp:3000/article/10.1101/2022.03.15.484463 2>&1 | grep 'Requests per second:' | awk '{print $4}'),\
$(ab -c100 -t 20 http://epp-node-http.epp:3000/article/10.1101/2022.03.15.484463 2>&1 | grep 'Requests per second:' | awk '{print $4}')" 
done

for iter in 1 2 3; do
    echo "testing CouchDB $iter..."
    echo "CouchDB,$iter,$(ab -c1   -t 20 http://epp-node-couchdb-http.epp:3000/article/10.1101/2022.03.15.484463 2>&1 | grep 'Requests per second:' | awk '{print $4}'),\
$(ab -c10  -t 20 http://epp-node-couchdb-http.epp:3000/article/10.1101/2022.03.15.484463 2>&1 | grep 'Requests per second:' | awk '{print $4}'),\
$(ab -c20  -t 20 http://epp-node-couchdb-http.epp:3000/article/10.1101/2022.03.15.484463 2>&1 | grep 'Requests per second:' | awk '{print $4}'),\
$(ab -c50  -t 20 http://epp-node-couchdb-http.epp:3000/article/10.1101/2022.03.15.484463 2>&1 | grep 'Requests per second:' | awk '{print $4}'),\
$(ab -c100 -t 20 http://epp-node-couchdb-http.epp:3000/article/10.1101/2022.03.15.484463 2>&1 | grep 'Requests per second:' | awk '{print $4}')" 
done
```

and this output:
```
SQLite,1,47.10,46.13,51.11,57.96,44.42
SQLite,2,49.01,57.56,47.84,50.50,52.58
SQLite,3,46.10,52.42,52.62,51.58,49.07
CouchDB,1,4.91,10.51,11.17,11.22,8.38
CouchDB,2,3.64,9.29,10.64,9.80,7.80
CouchDB,3,4.43,9.33,10.11,9.46,8.29
```

Confirming the CouchDB is creating a performance hit around 5-6x slower compared to SQLite local container file. Both containers used a full CPU when under benchmarking, so scaling the container is possibly the only way to increase scalability if we needed it.

**Comment by scottaubrey** [comment]
There are quite a few bugs (some listed above) that need to be ironed out before we can reliably change backend.

**Comment by scottaubrey** [comment]
Finally, I've written a repo backend for MongoDB, to get a simple networked-DB comparison. It performs close to, but slightly faster than pouchDB with a local DB, and slower than SQLite (obviously, with a local DB). This is about where I would expect it to be (maybe might have guessed slightly slower than Pouch-local), and puts it around ~2.5-4x faster than CouchDB. 

We can conclude a few things:
- CouchDB is slow, and resource hungry.
- PouchDB is faster than nano as a client library against networked CouchDB, but not hugely.
- PouchDB additionally gives us a way to run tests suite without an additional service (though I have found [this](https://github.com/chris-l/mock-couch) too)
- writing a new repo is really quick (about 20-30 mins this morning for MongoDB), because our database usage is really easy right now (and probably will be for the foreseeable future).

Additionally, for other database there are plenty of k8s operators, hosted services, etc, but Couch's community is so small that even the k8s operator fell off the internet and there's only a few announcements about it as evidence it ever existed. There's the hosted service exclusive to IBM cloud, and that's about it. I'm now assuming I will need to build our our day-2 activities (backup, restore, upgrades) pretty much from scratch on the cluster, which feels like it's not the right thing for me to spend time on if we can help it.

@will-byrne @nlisgo I think we should have a discussion specifically about if the positives of CouchDB are going to be realised - namely the ability to sync data (particularly if we can use it instead of an API for the client). If not, I'm not sure that the overheads of using it make sense, much as I love the concept and Fauton :)

I've pushed up the branch with all the repos in [here](https://github.com/elifesciences/enhanced-preprints/compare/master...mongo-and-pouch-repos) if you want to take a look.

**Comment by will-byrne** [comment]
I just discovered today I made a mistake in some of the couchdb work and we are storing the xml, html, and json twice so that may throw off the metrics slightly with all of that image data duplicated 4 times.

(in the store method we spread the article and so it adds all of the fields and not just the ones in the type_

**Comment by scottaubrey** [comment]
Pushed some changes in line with what @will-byrne said [here](https://github.com/elifesciences/enhanced-preprints/commit/a745d6fbc1459070365546d3afc094991b19fb2b). Re-benchmarked and it's helped performance a little, but not by much. It's helped pouchdb-local deliver more thoughput, now higher than mongodb (which is what I expected originally). pouch and nano backed by a real couchdb still remain quite constrained compared to every other backend. However, I've not looked to see if there is a positive impact to the couchdb cluster resources from this change as that would need an image to be built and deployed - probably best done as a separate changeset from master.

**Comment by scottaubrey** [comment]
Finally got the [MongoDB deployed](https://github.com/elifesciences/elife-flux-test/tree/master/deployments/epp-node-mongodb/mongodb), and all the [user permissions sorted](https://github.com/elifesciences/elife-flux-test/blob/master/deployments/epp-node-mongodb/deployment.yaml#L33).

Added MongoDB to the benchmark script and tweaked the ordering a little. Ran it again (making sure running from the node without the web service pods running on it again):
```
MongoDB,1,35.91,46.36,47.34,47.71,46.04
MongoDB,2,37.92,52.26,49.49,49.59,48.21
MongoDB,3,37.45,49.49,51.17,47.83,47.47
CouchDB,1,4.91,10.87,9.98,9.87,8.04
CouchDB,2,3.83,9.49,9.79,9.41,8.54
CouchDB,3,3.42,8.73,9.72,9.29,9.12
SQLite,1,141.43,290.23,311.31,303.41,267.49
SQLite,2,183.93,292.97,304.89,312.83,268.73
SQLite,3,190.95,287.26,316.25,309.22,270.95
```

So still a performance hit compared with SQLite as expected, but not as significant as with CouchDB.

Also, saw the pod CPU spike for each in turn as before:


![Image](https://user-images.githubusercontent.com/375812/185337694-f3cad391-d0fc-4e74-9bb2-ff18dcfaa0b6.png)


but the database cluster's CPU difference is stark:


![Image](https://user-images.githubusercontent.com/375812/185337795-55a39149-2873-4207-9803-a058d44177e5.png)

Those two charts are for the same time period, and you can just about see a slight blip to CPU usage while the mongodb app pod is being tested. This is good, it implies we can scale the number of pods up, and the database won't struggle. However, we see the same massive CPU usage from the couchdb cluster when it is being tested, implying that it's bottlenecking in the database cluster.

And just because the results are so different, and even though locally we do see similar difference, I wanted to double check a few things about their setup to make sure it wasn't something in the config:
- Both clusters are running a pod per node:
```
    NAME                                READY   STATUS    RESTARTS   AGE     IP            NODE                          NOMINATED NODE   READINESS GATES
epp-db-couchdb-0                    2/2     Running   0          62d     10.0.12.125   ip-10-0-12-91.ec2.internal    <none>           <none>
epp-db-couchdb-1                    2/2     Running   0          62d     10.0.11.103   ip-10-0-11-137.ec2.internal   <none>           <none>
epp-db-couchdb-2                    2/2     Running   0          62d     10.0.11.117   ip-10-0-11-202.ec2.internal   <none>           <none>
mongodb-rs0-0                       1/1     Running   0          42h     10.0.11.30    ip-10-0-11-137.ec2.internal   <none>           <none>
mongodb-rs0-1                       1/1     Running   0          42h     10.0.12.216   ip-10-0-12-91.ec2.internal    <none>           <none>
mongodb-rs0-2                       1/1     Running   0          42h     10.0.11.125   ip-10-0-11-202.ec2.internal   <none>           <none>
```

- the config for the database deployments to make sure they were both using local disks:
```
> kubectl get statefulset -n epp mongodb-rs0 -o yaml | yq .spec.template.spec.volumes
<snip>
- emptyDir: {}
  name: mongod-data
<snip>

> kubectl get statefulset -n epp epp-db-couchdb -o yaml | yq .spec.template.spec.volumes
<snip>
- emptyDir: {}
  name: database-storage
<snip>
```
