### ISSUE TITLE
Make a decision on client server architecture

### ISSUE THREAD

**Issue by will-byrne** [elifesciences/enhanced-preprints-server#217]
# Description

To decide how to create and update a client application separate from the server application

# Task

- [x] Create React app
- [x] building components towards a page
- [x] Create server side-render framework 
- [x] Decide how to move forward

**Comment by scottaubrey** [comment]
NextJS server-side framework branch: https://github.com/elifesciences/enhanced-preprints-client/tree/add-page-nextjs
