### ISSUE TITLE
Setup EPP prod environment

### ISSUE THREAD

**Issue by scottaubrey** [elifesciences/enhanced-preprints-server#406]
# Description

To ensure isolation of services, we should create a production environment for EPP.

# Tasks

- [x] Create kustomize cnofiguration for EPP based on current staging environment config
- [x] Deploy MongoDB operator to `flux-prod` cluster 
  - https://github.com/elifesciences/elife-flux-cluster/pull/814
  - https://github.com/elifesciences/elife-flux-cluster/pull/816
- [x] Redeploy staging--epp to the `flux-prod` cluster using the new kustomize config
- [ ] ~Redeploy `epp-api-dummy` to the `flux-prod` cluster~
- [ ] ~Redeploy `storybook` to the `flux-prod` cluster~
- [ ] ~Remove `epp--staging` config from the `flux-test` cluster~
- [x] Deploy prod--epp to the `flux-prod` cluster using the new kustomize config 
  - https://github.com/elifesciences/elife-flux-cluster/pull/815 

# Definition of done

- [x] https://staging--epp.elifesciences.org is up, and hitting the production cluster
- [x] https://prod--epp.elifesciences.org is up, and hitting the production cluster 
- [ ] ~the `flux-test` cluster has no production services running.~

Note: clean up actions moved to https://github.com/elifesciences/enhanced-preprints-server/issues/432

**Comment by scottaubrey** [comment]
Increased the number of nodes available in the cluster this morning to allow for growth over the next few days as traffic starts coming in
