### ISSUE TITLE
NewRelic integration into EPP

### ISSUE THREAD

**Issue by scottaubrey** [elifesciences/enhanced-preprints-server#407]
# Definition of Done

To provide insight into performance and errors across services, we should aim to integrate EPP into NewRelic like other eLife services.

# Tasks

- [ ] Investigate NR agent integration for node.js environments
- [ ] Implement NR integration into node.js in `epp-server`
- [ ] - [ ] Implement NR integration into node.js in `epp-client`

Definition of Done

- [ ] Data for client and server for `staging--epp` and `prod--epp` appears in the correct newrelic environment.
