### ISSUE TITLE
Add announcement URLs

### ISSUE THREAD

**Issue by QueenKraken** [elifesciences/enhanced-preprints-server#416]
# User Story

As an eLife reader I would like links to take me to further information about the announcement so I stay informed

### What is the benefit of solving the problem?

By flagging our change we can promote our new model and gain buy in from subscribers

### How will we know when the problem has been solved?

Each link will take the user to the correct, corresponding page

# Acceptance Criteria

- [ ] Press release https://elifesciences.org/for-the-press/b2329859 
- [ ] Inside eLife 1 (for authors) https://elifesciences.org/inside-elife/54d63486   
- [ ] Inside eLife 2 (on eLife assessments) https://elifesciences.org/inside-elife/db24dd46  

# Tasks

<!--
List of any initial tasks, if applicable, that you think might need to be done to progress this issue. e.g...
- [ ]

**Comment by scottaubrey** [comment]
@chris-huggins Are these links supposed to go somewhere in EPP?

**Comment by chris-huggins** [comment]
@scottaubrey Only the "Inside eLife 2" will be linked to from the EPP article pages. It's via the text "About eLife assessments" at the bottom of the eLife assessment box.

This is the ticket for that work: https://github.com/elifesciences/enhanced-preprints-server/issues/428

**Comment by nlisgo** [comment]
Is there anything more needed from me here?

**Comment by chris-huggins** [comment]
@nlisgo I think that's it. This ticket covers including the links in EPP, but we had a duplicate so I think this can be closed.

**Comment by nlisgo** [comment]
This is closing.
