### ISSUE TITLE
EPP Announcement - Switch on

### ISSUE THREAD

**Issue by QueenKraken** [elifesciences/enhanced-preprints-server#417]
# User Story

As an eLife reader I would like to see the demos and articles live on the site after the announcement to understand the change

### What is the benefit of solving the problem?

Switching on and validating supports our goals

### How will we know when the problem has been solved?

All released development will be live and validated in production

# Acceptance Criteria

- [ ] Estimate validation time - reviewed pre prints to be checked, Production team to update content
- [ ] Estimate caching time - 1 hour
- [ ] Determine switch on time - highlights & hero banner needs to co-ordinate with this
- [ ] Detail go live process
- [ ] Execute above plan

# Tasks

<!--
List of any initial tasks, if applicable, that you think might need to be done to progress this issue. e.g...
- [ ]
