### ISSUE TITLE
Remove Reviewed Pre Prints

### ISSUE THREAD

**Issue by QueenKraken** [elifesciences/enhanced-preprints-server#440]
# Description

As an eLife reader I want all reviewed pre prints to be standardised to prevent unnecessary confusion

### What is the benefit of solving the problem?

By removing RPP with reduced data we provided a stronger product view to readers

### How will we know when the problem has been solved?

Listed RPPs will not show

# Documents and Resources

- [ ] https://staging--epp.elifesciences.org/reviewed-preprints/80993 - to be removed
- [ ] https://staging--epp.elifesciences.org/reviewed-preprints/81274 - to be removed
- [ ] https://staging--epp.elifesciences.org/reviewed-preprints/81926 - may need to be removed depending on Fred's PR https://github.com/elifesciences/enhanced-preprints-data/pull/2 

# Tasks

List of any initial tasks, if applicable, that you think might need to be done to progress this issue. e.g...
- [ ] Remove the top two RPPs
- [ ] Check the above PR to determine if the third RPP should be removed, remove is necessary
