### ISSUE TITLE
Resolve missing back matter

### ISSUE THREAD

**Issue by QueenKraken** [elifesciences/enhanced-preprints-server#441]
# Description

As an eLife reader I would like all back matter to be published so I can have the relevant information attached to each article

### What is the benefit of solving the problem?

Our new PRC process will mirror publishing industry standards

### How will we know when the problem has been solved?

Each back matter item will be published as standard

# Acceptance Criteria

- [ ] Author affiliations (in another ticket)
- [ ] Corresponding author status
- [ ] Author contributions
- [ ] Supplementary figures
- [ ] Supporting information display correctly(removed for launch)
- [ ] Acknowledgements
- [ ] Issue information in References
- [ ] Journal Title in References
- [ ] eLocation in References
- [ ] Info missing for ref Lenth 2010 (versioning info)
- [ ] Publisher for book references (e.g Lynch and Walsh, 1998)
- [ ] Author information 
- [ ] Affiliation order: GEREC, Methodology center, FIMM
- [ ] Reference Information to include journal name, elocation and DOIs
- [ ] Funding 
- [ ] Competing interests
- [ ] Data availability
- [ ] ORCIDS
- [ ] 

# Examples of back matter not working

- [ ] https://docs.google.com/document/d/1HG9zjG_VIIZZpeetcka-9uoPOzO9G9ehTiKbxPRK-mY/edit# Feedback form with more info
- [ ] [[Mockup About page](https://projects.invisionapp.com/share/SV12W690NYDM#/screens/468581755)](https://staging--epp.elifesciences.org/reviewed-preprints/80993)
- [ ] https://staging--epp.elifesciences.org/reviewed-preprints/80729
- [ ] https://staging--epp.elifesciences.org/reviewed-preprints/81727)
- [ ] https://staging--epp.elifesciences.org/reviewed-preprints/80494
- [ ] https://staging--epp.elifesciences.org/reviewed-preprints/81926

# Tasks

- [ ] 

# Definition of Done

- [ ] Solution deployed to a staging environment.
- [ ] Solution reviewed and approved by @chris-huggins 
- [ ] Solution reviewed and approved by @QueenKraken 
- [ ] Solution reviewed and approved by @nlisgo 
- [ ] Solution deployed to production.

**Comment by QueenKraken** [comment]
This work is dependant on the outcome of @BlueReZZ conversation with Encoda.
