### ISSUE TITLE
Resolve visual inconsistencies

### ISSUE THREAD

**Issue by QueenKraken** [elifesciences/enhanced-preprints-server#442]
# Description

As an eLife reader I would like reviewed pre prints to be accurately rendered and polished to demonstrate professional standards

### What is the benefit of solving the problem?

RPP should be visually standardised with minimal hardcoding/dev work

### How will we know when the problem has been solved?

Each RPP will display consistently

# Acceptance Criteria

- [ ] If section labels appear they should use the same formatting (removed for launch)
- [ ] Brackets should be used appropriately, see example
- [ ] Inline equations  and/or graphics to be centred
- [ ] Equations to appear in figures and data tab
- [ ] Abstract currently displays in sentence case but other sections including preprint displays in uppercase (maybe resolved as part of https://www.google.com/url?q=https://github.com/elifesciences/enhanced-preprints-data/pull/3&sa=D&source=docs&ust=1666181512702130&usg=AOvVaw1pyp4Y9TrVHwmgJXpnL0ns ) 
- [ ] Editors: currently display as senior-editor and editor. Should display as Senior Editor and Editor
- [ ] Formatting of table titles to be standardised - revisit restyling work completed for launch 
- [ ] Headings should not be in caps (fixed for launch, may require more work)
- [ ] Ensure figures have corresponding legends
- [ ] Clickable citations (to figure supplements)
- [ ] Equal contribution status for the first two authors as standard

# Examples of inconsistencies 

- [ ] To help resolve these problems, and following (Etterson and Shaw (2001)**)** and (Morrissey et al. (2012)**)** among others, (Stinchcombe et al. (2014)**)** have proposed

- [ ] https://docs.google.com/document/d/1HG9zjG_VIIZZpeetcka-9uoPOzO9G9ehTiKbxPRK-mY/edit# Feedback form with more info
- [ ] [[Mockup About page](https://projects.invisionapp.com/share/SV12W690NYDM#/screens/468581755)](https://staging--epp.elifesciences.org/reviewed-preprints/80993)
- [ ] https://staging--epp.elifesciences.org/reviewed-preprints/80729
- [ ] https://staging--epp.elifesciences.org/reviewed-preprints/81727)
- [ ] https://staging--epp.elifesciences.org/reviewed-preprints/80494
- [ ] https://staging--epp.elifesciences.org/reviewed-preprints/81926

# Tasks

- [ ] 

# Definition of Done

- [ ] Solution deployed to a staging environment.
- [ ] Solution reviewed and approved by @chris-huggins 
- [ ] Solution reviewed and approved by @QueenKraken 
- [ ] Solution reviewed and approved by @nlisgo 
- [ ] Solution deployed to production.

**Comment by discodavey** [comment]
I have moved this back to the Todo list as tickets within here need more information and looks like a lot of the work will need to be done from the XML side rather than CSS changes
