### ISSUE TITLE
Review of existing css / html for accessibility and naming

### ISSUE THREAD

**Issue by will-byrne** [elifesciences/enhanced-preprints-server#47]
# Tasks:
- [ ] #141

**Comment by scottaubrey** [comment]
@discodavey This was the ticket I mentioned - at point of writing is at the top of the backlog

**Comment by discodavey** [comment]
@chris-huggins Can you define the font sizes and line-heights for alll the h tags please

**Comment by chris-huggins** [comment]
Sure I can look at this tomorrow.

**Comment by discodavey** [comment]
After the first pass this is what we have found that will need to be changed or reviewed. We have left the main content area as this may change if the content is brought in via json which will make it easier to style and make the code more semantic.

**Content Header**

- [ ] eLife logo needs text using text indent
- [ ] Content attribute in h1 to be remove as not needed
- [ ] Swap content header div to be header tag
- [ ] Authors list needs aria label
- [ ] Affiliations list needs aria label
- [ ] Primary and secondary columns need to switch for source order

**Secondary column**

- [ ] Move article-furniture to same div as secondary column div
- [ ] Paragraph should be in p tag not span
- [ ] Article actions to be a list either ul or ol
- [ ] All icons to be downloaded as svgs and used as background images
- [ ] Review timeline - think about how to layout?
- [ ] Article metadata - review later when content gets dynamically pulled in

**Jump to menu**

- [ ] Should be in a nav tag

**Primary column**

- [ ] Class primary-column should be a div
- [ ] Main-content-area should be in a main tag

More advanced accessibility may need to be added like aria-labels etc but we  can do this further down the road.

**Comment by chris-huggins** [comment]
@discodavey 
> @chris-huggins Can you define the font sizes and line-heights for all the h tags please
<img width="763" alt="image" src="https://user-images.githubusercontent.com/41907215/175993210-21bd6b08-5d5f-4022-b53d-f37d6d83ca3a.png">

**Comment by scottaubrey** [comment]
@discodavey Thinks this is done, but with some outstanding tasks in #141
