### ISSUE TITLE
Mastadon set up

### ISSUE THREAD

**Issue by QueenKraken** [elifesciences/enhanced-preprints-server#511]
# Description

As an eLife user I would like eLife to be present on social media site, Mastadon so I can engage 

# Acceptance Criteria

- [ ] Mastadon to be added to https://elifesciences.org/ 
- [ ] Mastadon to be added to https://elifesciences.org/about 
- [ ] eLife to be verified

# Screenshots

![Image](https://user-images.githubusercontent.com/113016345/200589051-af0474ae-b8f3-4856-9414-d2050fadf993.png)

![Image](https://user-images.githubusercontent.com/113016345/200589126-43ac72b1-1cea-4c09-be59-df3b8e768691.png)

# Tasks

- [ ]

**Comment by QueenKraken** [comment]
Blocked until Daisy provides full link and sign on details.

**Comment by scottaubrey** [comment]
FYI @DaisyVeysey

**Comment by QueenKraken** [comment]
@discodavey ticket unblocked as info received from Daisy and added to A/C

**Comment by DaisyVeysey** [comment]
Thanks, everyone! Any chance you could include the link to the IE about the new model:https://elifesciences.org/inside-elife/54d63486/elife-s-new-model-changing-the-way-you-share-your-research

...either instead of the about page or as well as?

P.s. I have a lot of trouble logging into Mastodon and often have to go through my invite email. The details are correct, but if you get problems too, I'll see if I can help.
