### ISSUE TITLE
Validate Nokome's work

### ISSUE THREAD

**Issue by QueenKraken** [elifesciences/enhanced-preprints-server#514]
# Description

As a stencil dev I would like to know the work I have completed for eLife to date is progressing in the right direction to check quality

# Acceptance criteria

- [ ] Check the code https://github.com/stencila/encoda/pull/1031 
- [ ] Review JSON files https://github.com/stencila/encoda/pull/1031/files#diff-330fd693ca22844748c82d1b59e510174892bebca3599e94ec2545d2d705493b 
- [ ] Run above files
- [ ] Capture and share feedback to Nokome via @queenkraken

# Tasks

- [ ]
